# Generated by Django 5.0 on 2024-01-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_goodsnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.CharField(max_length=255)),
                ('goodsid', models.CharField(max_length=255)),
                ('userid', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notes_goods',
            },
        ),
        migrations.DeleteModel(
            name='GoodsNote',
        ),
    ]
