# Generated by Django 5.0 on 2024-01-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_delete_goodsnote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.AlterModelTable(
            name='note',
            table='note_tbs',
        ),
    ]
