# Generated by Django 5.0 on 2024-01-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='goods_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='store_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
