# Generated by Django 5.0 on 2024-01-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_note_goods_id_alter_note_store_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodsnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.IntegerField()),
                ('goodsid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('commend', models.TextField()),
            ],
            options={
                'db_table': 'GoodsNote',
            },
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
